name: Synchronize Non-application updates to all other branches 

on:
  push:
    branches:
      - master
    paths-ignore:
        - 'roomchat-frontend/**'
        - 'roomchat-backend/**'
        - 'contracts/**'
        - '!roomchat-frontend/**/*.md'
        - '!roomchat-backend/**/*.md'
        - '!contracts/**/*.md'
  
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ github.token}}

      - name: Login, List branches and save branches information
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch --all
          git branch -r --format="%(refname:lstrip=3)" > branches.txt
          

      - name: Force merge non-code changes from Master to all branches
        run: |
          while IFS= read -r branch; do
            if [ "$branch" != "master" ]; then
              git checkout master
              git pull origin master
              git checkout temp-branch
              git checkout -f $branch
              git reset --hard origin/$branch  # Fix: Use $branch instead of master
              git add .
              git commit -m "Merge changes outside of frontend and backend folders"
              git push origin $branch --force
              git branch -d temp-branch
            fi
          done < branches.txt